const fs = require('fs');
const path = require('path');

const rawFile = 'C:\\Users\\MY-PC\\.gemini\\antigravity-ide\\brain\\82bb4da1-1d00-4253-b1fa-cc69bf1501b3\\scratch\\raw_mappings.txt';
const sqlFile = 'd:\\Documents\\Aavin R&D\\database\\societynumbers.sql';

const rawData = fs.readFileSync(rawFile, 'utf8');
const lines = rawData.split('\n').filter(l => l.trim().length > 0);

const mappings = [];
const seenCodes = new Set();
const excludedCodes = ['8456', '8689', '8712', '8519', '1416'];

for (const line of lines) {
  // Line format: "001. 3326 → 919943799341"
  const match = line.match(/^\d+\.\s+(\d+)\s+[→>]\s+(.+)$/);
  if (match) {
    const societyCode = match[1];
    let number = match[2].replace(/[\s\+\-]/g, ''); // normalize number

    if (excludedCodes.includes(societyCode)) {
      console.log(`Excluding invalid society code: ${societyCode}`);
      continue;
    }

    if (seenCodes.has(societyCode)) {
      console.log(`Duplicate society code found: ${societyCode}`);
      continue;
    }
    
    // Check if it's 12 digits starting with 91
    if (!/^91\d{10}$/.test(number)) {
      console.log(`Invalid number format for society ${societyCode}: ${number}`);
    }

    seenCodes.add(societyCode);
    mappings.push({ code: societyCode, number });
  } else {
    console.log(`Could not parse line: ${line}`);
  }
}

console.log(`Total valid mappings found: ${mappings.length}`);
if (mappings.length !== 554) {
  console.log('Error: expected 554 mappings!');
}

let sql = `-- Migration: Add Society WhatsApp Numbers
-- Description: Creates a new table for society contacts and inserts/upserts 554 mappings.
-- Created at: ${new Date().toISOString()}

CREATE TABLE IF NOT EXISTS public.society_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    society_code TEXT UNIQUE NOT NULL,
    whatsapp_number TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_society_contacts_society_code ON public.society_contacts(society_code);

INSERT INTO public.society_contacts (society_code, whatsapp_number)
VALUES
`;

const values = mappings.map(m => `    ('${m.code}', '${m.number}')`).join(',\n');
sql += values;
sql += `
ON CONFLICT (society_code)
DO UPDATE SET
    whatsapp_number = EXCLUDED.whatsapp_number,
    updated_at = timezone('utc'::text, now());
`;

const dir = path.dirname(sqlFile);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(sqlFile, sql, 'utf8');
console.log(`Successfully wrote SQL to ${sqlFile}`);
